### ISSUE TITLE
vida-git-1.rockspec doesn't set "inspect" module as dependency

### ISSUE THREAD

**Issue by gut** [nwhitehead/vida#1]
Running on LuaJIT I had this problem:

<pre>
$ luarocks install vida
Installing https://luarocks.org/vida-v1-8.src.rock...
Using https://luarocks.org/vida-v1-8.src.rock... switching to 'build' mode
Updating manifest for /usr/local/lib/luarocks/rocks
vida v1-8 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

$ cat > vida-example.lua
local vida = require('vida')

local fast = vida.compile(
    vida.interface [[
        // C interface
        int func(int, int);
    ]],
    vida.code [[
        // C implementation
        EXPORT int func(int a, int b) {
            return a + b;
        }
    ]])

print(fast.func(3, 5)) -- prints out 8
$ luajit vida-example.lua
luajit: /usr/local/share/lua/5.1/vida.lua:197: module 'inspect' not found:
        no field package.preload['inspect']
        no file './inspect.lua'
        no file '/usr/local/share/luajit-2.1.0-alpha/inspect.lua'
        no file '/usr/local/share/lua/5.1/inspect.lua'
        no file '/usr/local/share/lua/5.1/inspect/init.lua'
        no file './inspect.so'
        no file '/usr/local/lib/lua/5.1/inspect.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/vida.lua:197: in function </usr/local/share/lua/5.1/vida.lua:185>
        [C]: in function 'require'
        vida:1: in main chunk
        [C]: at 0x10006284
</pre>

I solved it with:

<pre>
$ luarocks install inspect
Installing https://luarocks.org/inspect-3.0-1.rockspec...
Using https://luarocks.org/inspect-3.0-1.rockspec... switching to 'build' mode
Updating manifest for /usr/local/lib/luarocks/rocks
inspect 3.0-1 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

$ luajit vida-example.lua
8
</pre>

Therefore I'd add `inspect` as a dependency.

System Info: luarocks also running LuaJIT on PPC64le machine (POWER8)

**Comment by amberwhitehead** [comment]
Thanks, good catch! I'm not even using it in the main module, took out the import line and updated the rocks.
